### ISSUE TITLE
Publishing it to gh-pages?

### ISSUE THREAD

**Issue by arthursoares** [BuckyMaler/jekyll-starter-kit#1]
Hey @BuckyMaler amazing work on this. The only question I have is how do you proceed in building the styles and everythiing to the `gh-pages` when pushing to my own repo?

Cheers.

**Comment by BuckyMaler** [comment]
Thanks @arthursoares! I understand your concern with pushing to `gh-pages`, but the leading styles question I don't quite understand. If you're referring to the CSS, all of the styles are written in `_assets/css`. Simply include an import in the `main.sass` for every Sass file you include and compilation will take care of its self. As for the `gh-pages` question. You'll want to push the `_site` directory to your `gh-pages` branch as usual. You can push a subfolder by following this gist. I've encountered issues in the past with this when publishing specifically to the [username].github.io repo. I believe GitHub displays the contents from the master branch for that particular repo. Therefore, in this case you'd want to push the `_site` directory to master.

I hope that helps.

**Comment by arthursoares** [comment]
Hey @BuckyMaler thanks for the answer.

I think I've solved it in a different way, basically added a couple of other `.pipe` instructions to each of the routine, so they'd process the files to the `/assets/` folder

Example:

```
// compile javascript
gulp.task('scripts', function() {
	return gulp
		.src(['_assets/js/vendor/*', '_assets/js/*.js'])
		.pipe(plumber({
			errorHandler: onError
		}))
		.pipe(jsHint())
    .pipe(jsHint.reporter('default'))
		.pipe(concat('main.js'))
    .pipe(gulp.dest('assets/js'))
		.pipe(gulp.dest('_site/assets/js'))
    .pipe(rename({suffix: '.min'}))
		.pipe(uglify())
		.pipe(gulp.dest('assets/js'))
		.pipe(gulp.dest('_site/assets/js'))
		.pipe(browserSync.reload({stream: true}));
});
```

This is working very well.

Thank you :)
